name: 'Label Actions'
description: 'Perform actions when issues or pull requests are labeled or unlabeled'
author: 'Armin Sebastian'
inputs:
  github-token:
    description: 'GitHub access token'
    default: '${{ github.token }}'
  config-path:
    description: 'Configuration file path'
    default: '.github/label-actions.yml'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'purple'
